### ISSUE TITLE
Crash trying to cast spell

### ISSUE THREAD

**Issue by aydjay** [RoseKavalier/H3Plugins#13]
[HD_CRASH_LOG.TXT](https://github.com/RoseKavalier/H3Plugins/files/5975669/HD_CRASH_LOG.TXT)
Attached save game, end turn, engage orange hero and cast a spell, crashes as soon as you hover over a unit

[147.zip](https://github.com/RoseKavalier/H3Plugins/files/5975671/147.zip)

**Comment by Benkrik** [comment]
Same here. Tan heroes casting Magic Arrow.

[[] HD_CRASH_LOG.TXT](https://github.com/RoseKavalier/H3Plugins/files/5975962/HD_CRASH_LOG.TXT)
[HD_CRASH_LOG.TXT](https://github.com/RoseKavalier/H3Plugins/files/5975963/HD_CRASH_LOG.TXT)

**Comment by RoseKavalier** [comment]
I messed something with text formatting, will be resolved asap.
