### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by beeheemooth** [RoseKavalier/H3Plugins#15]
Hi there! I am using latest SOD. I was able to reproduce the conditions under which the game crashes. 
This happens when for killing monsters resources or gold are given in amount of more than 999 (that is, a four-digit number). 

**Steps to reproduce** 

999 - ok

![ezgif-5-6bcd3de1de03](https://user-images.githubusercontent.com/25724133/107884238-9543e200-6efc-11eb-8ac9-c5dbeb929326.gif)

1000 - crash

![ezgif-5-11197273aa24](https://user-images.githubusercontent.com/25724133/107884247-a2f96780-6efc-11eb-905a-0396f7fe5fc4.gif)

**Comment by RoseKavalier** [comment]
Unable to reproduce with these steps, text output is correctly formatted.
![image](https://user-images.githubusercontent.com/25070750/107885695-cfe05700-6ec9-11eb-81ce-23a1f767a341.png)

Submit the crash logs please

**Comment by beeheemooth** [comment]
[HD_CRASH_LOG.ZIP](https://github.com/RoseKavalier/H3Plugins/files/5978548/HD_CRASH_LOG.ZIP)

**Comment by beeheemooth** [comment]
This crash occurs on any map where resources or more than 1000 gold are given for defeating monsters (artifacts don't lead to crash). Everything else works fine.

I tried converting the map to "Shadow of Death" and "Armageddon's Blade" but the result was the same. The game won't crash without a plugin. I reinstalled the game and the plugin but it didn't help. If the game with plugin crashes only for me, how can i solve this problem?

**Comment by RoseKavalier** [comment]
SoD_SP has its own debug folder with crash logs which are more complete and informative to me, the HDmod crash log has more or less nothing I can use to trace back.
`<...>/<SoD_SP>/Debug/`

I've done the same exact steps you posted and inspected the code region in this area and nothing odd happens on my end, so without all of those I'm totally clueless.

**Comment by beeheemooth** [comment]
Oops, I didn't know about that, sorry. 
[debug.zip](https://github.com/RoseKavalier/H3Plugins/files/5978673/debug.zip)

**Comment by RoseKavalier** [comment]
According to debug files, you're on 1.19.0.9 while the current version is 1.19.3.1.
Either update to latest version or check you don't have old files being loaded from somewhere.

**Comment by beeheemooth** [comment]
Strange, because I just re-updated the plugin today. Although I updated it a month ago, after that, for some reason, at startup, a window always appeared with a message that I was using an old version.
  It looks like the problem is in the game itself, maybe I accidentally changed something in it, I will need to download it again, and then install the plugin.
  Thanks for your time!

**Comment by beeheemooth** [comment]
The problem has been resolved. It did not touch the plug-in, but was in the game itself. After a complete reinstallation, everything works well. 
![ezgif-5-757e03346ce1](https://user-images.githubusercontent.com/25724133/107959605-4e152a00-6fac-11eb-86bb-35220934d98c.gif)
