### ISSUE TITLE
No longer compatible with HD Mod

### ISSUE THREAD

**Issue by Titania318** [RoseKavalier/H3Plugins#25]
From the new HD Mod update: "The game does not support the SoD_SP plugin version 1.9.3.11 and earlier due to incompatibility"

**Comment by RoseKavalier** [comment]
Yep, some internal things changed on HDmod's side and it's a precautionary change.
HDmod author and I are in touch and will be resolving this issue ASAP.

**Comment by Titania318** [comment]
Thank you. Glad to hear that.

**Comment by k-seb** [comment]
Hey, just wanted to ask what's the current status?

**Comment by paulpaul9740** [comment]
F.Y.I. at this moment you can use previous hd mod version ( Uninstall -> "Rollback last update" if you are already updated to last version)

**Comment by DemonCloud** [comment]
hopeful update
