### ISSUE TITLE
Compatibility issues

### ISSUE THREAD

**Issue by yuritsuki** [RoseKavalier/H3Plugins#29]
Does this plugin support NewSpells by AlexSpl? Got a crash while opening a hero screen after I picked up a scroll with the new spell. I can provide a crashlog if you canhelp.

**Comment by RoseKavalier** [comment]
No idea. No plans to support non-standard mods.

**Comment by yuritsuki** [comment]
> No idea. No plans to support non-standard mods.

Ok, i'll try to contact with AlexSpl.
