### ISSUE TITLE
В SoD SP не работает отключение месяца существ

### ISSUE THREAD

**Issue by LazyEnot** [RoseKavalier/H3Plugins#3]
Игра - Герои 3 HD полное собрание + Wineskin на MacOS

Установил последнюю версию плагина SoD SP, отключил месяцы/недели существ/чумы, но в карте продолжает возникать месяц троглодита. Карта специальная, существ дается очень мало, поэтому даже 30 троглодитов превращают карту в неиграбельную.

**Comment by RoseKavalier** [comment]
Hi,
I don't plan on doing non-code debug here, head to one of the official forums for SoD_SP for that. In any case, you should verify that:

1. SoD_SP is actually loaded
2. The *prevent monthly growth* option is disabled

**Comment by RoseKavalier** [comment]
Considering as closed.
