### ISSUE TITLE
Expect the new version to support HDmod's battlequeue

### ISSUE THREAD

**Issue by lionk007** [RoseKavalier/H3Plugins#30]
HD5.4R7 does not support the SoD_SP plugin version 1.9.3.11, but the latest HD5.4R84 supports the SoD_SP plugin version 1.9.3.11, so is it possible to add HDmod's battlequeue to the next SoD_SP plugin release? I'm really looking forward to this feature.

**Comment by RoseKavalier** [comment]
See [http://heroescommunity.com/viewthread.php3?TID=44581&PID=1577256#focus](http://heroescommunity.com/viewthread.php3?TID=44581&PID=1577256#focus)
