### ISSUE TITLE
Disabling check for update?

### ISSUE THREAD

**Issue by gavenkoa** [RoseKavalier/H3Plugins#4]
I want to disable check for update which opens dialog like:

![image](https://user-images.githubusercontent.com/273770/84672446-3c691780-af31-11ea-87df-9f616e72effc.png)

Could you make wiki or update README with link to `SoD_SP.ini` options?

**Comment by RoseKavalier** [comment]
There are extensive descriptions in 4-5 languages within `SoD_SP.ini`, a README would just be duplicating that.
Look for [other][CheckUpdate]

```
# During game launch, SoD_SP will attempt a single time to check if a new version of the plugin exists and if so ask the user whether to go to the download page. Disable if you do not wish to check.
# Во время запуска игры SoD_SP будет проверять наличие новой версии плагина. В случае успеха пользователю будет предложено перейти на страницу загрузки. Отключите, если не хотите проверять наличие обновлений.
#  Bei Spielstart wird SoD_SP ein einziges Mal versuchen zu prüfen, ob eine neue Version des Plugins besteht, und ob sie besteht, den Benutzer bitten, ob er zur Downloadseite gehen möchte. Deaktivieren Sie diese Option, ob Sie keine Prüfung möchten.
# Κατά την έναρξη του παιχνιδιού, το SoD_SP θα προσπαθήσει μία φορά να ελέγξει αν υπάρχει νεότερη έκδοση του plugin και, αν ναι, θα ρωτήσει τον χρήστη αν επιθυμεί να μεταβεί στην σελίδα μεταφόρτωσης. Απενεργοποιήστε την επιλογή αν δεν θέλετε να γίνει έλεγχος.
CheckUpdate = 0
```

**Comment by gavenkoa** [comment]
There is no mentioning of `SoD_SP.ini` in README on the front page.... https://github.com/RoseKavalier/H3Plugins

Also there is no README inside `SoD_SP.1.19.0.3.Files.zip`.

Originally I had hard time to find `SoD_SP.ini` as I forgot the way it was installed and looked on github & inside installation archive.

**Comment by gavenkoa** [comment]
Section about configuration referring to `SoD_SP.ini` & README inside distribution might be helpful.

**Comment by RoseKavalier** [comment]
You're absolutely right; I'll write something and link it.

**Comment by RoseKavalier** [comment]
I should have closed this back when I made the changes, thanks for the issue.

**Comment by gavenkoa** [comment]
README is perfect. Link to `SoD_SP.ini` provides everything I needed!
