### ISSUE TITLE
A part of conditional expression is always false/true

### ISSUE THREAD

**Issue by thehlopster** [RoseKavalier/H3Plugins#9]
https://github.com/RoseKavalier/H3Plugins/blob/668d6a7408bcdd9693d91effc41c3478c36161a2/H3API/lib/h3api/H3Dialogs/H3Dialogs.cpp#L1399-L1401
https://github.com/RoseKavalier/H3Plugins/blob/668d6a7408bcdd9693d91effc41c3478c36161a2/H3API/lib/h3api/H3String/H3String.cpp#L430-L432
https://github.com/RoseKavalier/H3Plugins/blob/668d6a7408bcdd9693d91effc41c3478c36161a2/H3API/lib/h3api/H3String/H3String.cpp#L437-L439
since `UINT` is `unsigned` it is never lower than 0, so this checks is unnecessary and can be removed

**Comment by RoseKavalier** [comment]
Merged [here](https://github.com/RoseKavalier/H3API/pull/2).
